name: Run Unit Tests

on: [push]

jobs:
    run-unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v6
              with:
                node-version: 24
                cache: 'npm'

            - run: npm ci

            - run: npm run test
              env:
                NODE_ENV: dev
                JWT_SECRET: mba123
                DATABASE_URL: postgres://postgres:password@localhost:5432/solid_test_db